export const API_V1_CONTACT_LIST = "API_V1_CONTACT_LIST"
export const API_V1_CONTACT_LIST_SUCCEEDED = "API_V1_CONTACT_LIST_SUCCEEDED"
export const API_V1_CONTACT_LIST_FAILED = "API_V1_CONTACT_LIST_FAILED"
export const API_V1_CONTACT_CREATE = "API_V1_CONTACT_CREATE"
export const API_V1_CONTACT_CREATE_SUCCEEDED = "API_V1_CONTACT_CREATE_SUCCEEDED"
export const API_V1_CONTACT_CREATE_FAILED = "API_V1_CONTACT_CREATE_FAILED"
export const API_V1_CONTACT_READ = "API_V1_CONTACT_READ"
export const API_V1_CONTACT_READ_SUCCEEDED = "API_V1_CONTACT_READ_SUCCEEDED"
export const API_V1_CONTACT_READ_FAILED = "API_V1_CONTACT_READ_FAILED"
export const API_V1_CONTACT_UPDATE = "API_V1_CONTACT_UPDATE"
export const API_V1_CONTACT_UPDATE_SUCCEEDED = "API_V1_CONTACT_UPDATE_SUCCEEDED"
export const API_V1_CONTACT_UPDATE_FAILED = "API_V1_CONTACT_UPDATE_FAILED"
export const API_V1_CONTACT_PARTIAL_UPDATE = "API_V1_CONTACT_PARTIAL_UPDATE"
export const API_V1_CONTACT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CONTACT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CONTACT_PARTIAL_UPDATE_FAILED =
  "API_V1_CONTACT_PARTIAL_UPDATE_FAILED"
export const API_V1_CONTACT_DELETE = "API_V1_CONTACT_DELETE"
export const API_V1_CONTACT_DELETE_SUCCEEDED = "API_V1_CONTACT_DELETE_SUCCEEDED"
export const API_V1_CONTACT_DELETE_FAILED = "API_V1_CONTACT_DELETE_FAILED"
export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_FORWARDEDMESSAGE_LIST = "API_V1_FORWARDEDMESSAGE_LIST"
export const API_V1_FORWARDEDMESSAGE_LIST_SUCCEEDED =
  "API_V1_FORWARDEDMESSAGE_LIST_SUCCEEDED"
export const API_V1_FORWARDEDMESSAGE_LIST_FAILED =
  "API_V1_FORWARDEDMESSAGE_LIST_FAILED"
export const API_V1_FORWARDEDMESSAGE_CREATE = "API_V1_FORWARDEDMESSAGE_CREATE"
export const API_V1_FORWARDEDMESSAGE_CREATE_SUCCEEDED =
  "API_V1_FORWARDEDMESSAGE_CREATE_SUCCEEDED"
export const API_V1_FORWARDEDMESSAGE_CREATE_FAILED =
  "API_V1_FORWARDEDMESSAGE_CREATE_FAILED"
export const API_V1_FORWARDEDMESSAGE_READ = "API_V1_FORWARDEDMESSAGE_READ"
export const API_V1_FORWARDEDMESSAGE_READ_SUCCEEDED =
  "API_V1_FORWARDEDMESSAGE_READ_SUCCEEDED"
export const API_V1_FORWARDEDMESSAGE_READ_FAILED =
  "API_V1_FORWARDEDMESSAGE_READ_FAILED"
export const API_V1_FORWARDEDMESSAGE_UPDATE = "API_V1_FORWARDEDMESSAGE_UPDATE"
export const API_V1_FORWARDEDMESSAGE_UPDATE_SUCCEEDED =
  "API_V1_FORWARDEDMESSAGE_UPDATE_SUCCEEDED"
export const API_V1_FORWARDEDMESSAGE_UPDATE_FAILED =
  "API_V1_FORWARDEDMESSAGE_UPDATE_FAILED"
export const API_V1_FORWARDEDMESSAGE_PARTIAL_UPDATE =
  "API_V1_FORWARDEDMESSAGE_PARTIAL_UPDATE"
export const API_V1_FORWARDEDMESSAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_FORWARDEDMESSAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_FORWARDEDMESSAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_FORWARDEDMESSAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_FORWARDEDMESSAGE_DELETE = "API_V1_FORWARDEDMESSAGE_DELETE"
export const API_V1_FORWARDEDMESSAGE_DELETE_SUCCEEDED =
  "API_V1_FORWARDEDMESSAGE_DELETE_SUCCEEDED"
export const API_V1_FORWARDEDMESSAGE_DELETE_FAILED =
  "API_V1_FORWARDEDMESSAGE_DELETE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_MESSAGE_LIST = "API_V1_MESSAGE_LIST"
export const API_V1_MESSAGE_LIST_SUCCEEDED = "API_V1_MESSAGE_LIST_SUCCEEDED"
export const API_V1_MESSAGE_LIST_FAILED = "API_V1_MESSAGE_LIST_FAILED"
export const API_V1_MESSAGE_CREATE = "API_V1_MESSAGE_CREATE"
export const API_V1_MESSAGE_CREATE_SUCCEEDED = "API_V1_MESSAGE_CREATE_SUCCEEDED"
export const API_V1_MESSAGE_CREATE_FAILED = "API_V1_MESSAGE_CREATE_FAILED"
export const API_V1_MESSAGE_READ = "API_V1_MESSAGE_READ"
export const API_V1_MESSAGE_READ_SUCCEEDED = "API_V1_MESSAGE_READ_SUCCEEDED"
export const API_V1_MESSAGE_READ_FAILED = "API_V1_MESSAGE_READ_FAILED"
export const API_V1_MESSAGE_UPDATE = "API_V1_MESSAGE_UPDATE"
export const API_V1_MESSAGE_UPDATE_SUCCEEDED = "API_V1_MESSAGE_UPDATE_SUCCEEDED"
export const API_V1_MESSAGE_UPDATE_FAILED = "API_V1_MESSAGE_UPDATE_FAILED"
export const API_V1_MESSAGE_PARTIAL_UPDATE = "API_V1_MESSAGE_PARTIAL_UPDATE"
export const API_V1_MESSAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MESSAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MESSAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_MESSAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_MESSAGE_DELETE = "API_V1_MESSAGE_DELETE"
export const API_V1_MESSAGE_DELETE_SUCCEEDED = "API_V1_MESSAGE_DELETE_SUCCEEDED"
export const API_V1_MESSAGE_DELETE_FAILED = "API_V1_MESSAGE_DELETE_FAILED"
export const API_V1_MESSAGEACTION_LIST = "API_V1_MESSAGEACTION_LIST"
export const API_V1_MESSAGEACTION_LIST_SUCCEEDED =
  "API_V1_MESSAGEACTION_LIST_SUCCEEDED"
export const API_V1_MESSAGEACTION_LIST_FAILED =
  "API_V1_MESSAGEACTION_LIST_FAILED"
export const API_V1_MESSAGEACTION_CREATE = "API_V1_MESSAGEACTION_CREATE"
export const API_V1_MESSAGEACTION_CREATE_SUCCEEDED =
  "API_V1_MESSAGEACTION_CREATE_SUCCEEDED"
export const API_V1_MESSAGEACTION_CREATE_FAILED =
  "API_V1_MESSAGEACTION_CREATE_FAILED"
export const API_V1_MESSAGEACTION_READ = "API_V1_MESSAGEACTION_READ"
export const API_V1_MESSAGEACTION_READ_SUCCEEDED =
  "API_V1_MESSAGEACTION_READ_SUCCEEDED"
export const API_V1_MESSAGEACTION_READ_FAILED =
  "API_V1_MESSAGEACTION_READ_FAILED"
export const API_V1_MESSAGEACTION_UPDATE = "API_V1_MESSAGEACTION_UPDATE"
export const API_V1_MESSAGEACTION_UPDATE_SUCCEEDED =
  "API_V1_MESSAGEACTION_UPDATE_SUCCEEDED"
export const API_V1_MESSAGEACTION_UPDATE_FAILED =
  "API_V1_MESSAGEACTION_UPDATE_FAILED"
export const API_V1_MESSAGEACTION_PARTIAL_UPDATE =
  "API_V1_MESSAGEACTION_PARTIAL_UPDATE"
export const API_V1_MESSAGEACTION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MESSAGEACTION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MESSAGEACTION_PARTIAL_UPDATE_FAILED =
  "API_V1_MESSAGEACTION_PARTIAL_UPDATE_FAILED"
export const API_V1_MESSAGEACTION_DELETE = "API_V1_MESSAGEACTION_DELETE"
export const API_V1_MESSAGEACTION_DELETE_SUCCEEDED =
  "API_V1_MESSAGEACTION_DELETE_SUCCEEDED"
export const API_V1_MESSAGEACTION_DELETE_FAILED =
  "API_V1_MESSAGEACTION_DELETE_FAILED"
export const API_V1_PROFILE_LIST = "API_V1_PROFILE_LIST"
export const API_V1_PROFILE_LIST_SUCCEEDED = "API_V1_PROFILE_LIST_SUCCEEDED"
export const API_V1_PROFILE_LIST_FAILED = "API_V1_PROFILE_LIST_FAILED"
export const API_V1_PROFILE_CREATE = "API_V1_PROFILE_CREATE"
export const API_V1_PROFILE_CREATE_SUCCEEDED = "API_V1_PROFILE_CREATE_SUCCEEDED"
export const API_V1_PROFILE_CREATE_FAILED = "API_V1_PROFILE_CREATE_FAILED"
export const API_V1_PROFILE_READ = "API_V1_PROFILE_READ"
export const API_V1_PROFILE_READ_SUCCEEDED = "API_V1_PROFILE_READ_SUCCEEDED"
export const API_V1_PROFILE_READ_FAILED = "API_V1_PROFILE_READ_FAILED"
export const API_V1_PROFILE_UPDATE = "API_V1_PROFILE_UPDATE"
export const API_V1_PROFILE_UPDATE_SUCCEEDED = "API_V1_PROFILE_UPDATE_SUCCEEDED"
export const API_V1_PROFILE_UPDATE_FAILED = "API_V1_PROFILE_UPDATE_FAILED"
export const API_V1_PROFILE_PARTIAL_UPDATE = "API_V1_PROFILE_PARTIAL_UPDATE"
export const API_V1_PROFILE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PROFILE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PROFILE_PARTIAL_UPDATE_FAILED =
  "API_V1_PROFILE_PARTIAL_UPDATE_FAILED"
export const API_V1_PROFILE_DELETE = "API_V1_PROFILE_DELETE"
export const API_V1_PROFILE_DELETE_SUCCEEDED = "API_V1_PROFILE_DELETE_SUCCEEDED"
export const API_V1_PROFILE_DELETE_FAILED = "API_V1_PROFILE_DELETE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const API_V1_THREAD_LIST = "API_V1_THREAD_LIST"
export const API_V1_THREAD_LIST_SUCCEEDED = "API_V1_THREAD_LIST_SUCCEEDED"
export const API_V1_THREAD_LIST_FAILED = "API_V1_THREAD_LIST_FAILED"
export const API_V1_THREAD_CREATE = "API_V1_THREAD_CREATE"
export const API_V1_THREAD_CREATE_SUCCEEDED = "API_V1_THREAD_CREATE_SUCCEEDED"
export const API_V1_THREAD_CREATE_FAILED = "API_V1_THREAD_CREATE_FAILED"
export const API_V1_THREAD_READ = "API_V1_THREAD_READ"
export const API_V1_THREAD_READ_SUCCEEDED = "API_V1_THREAD_READ_SUCCEEDED"
export const API_V1_THREAD_READ_FAILED = "API_V1_THREAD_READ_FAILED"
export const API_V1_THREAD_UPDATE = "API_V1_THREAD_UPDATE"
export const API_V1_THREAD_UPDATE_SUCCEEDED = "API_V1_THREAD_UPDATE_SUCCEEDED"
export const API_V1_THREAD_UPDATE_FAILED = "API_V1_THREAD_UPDATE_FAILED"
export const API_V1_THREAD_PARTIAL_UPDATE = "API_V1_THREAD_PARTIAL_UPDATE"
export const API_V1_THREAD_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_THREAD_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_THREAD_PARTIAL_UPDATE_FAILED =
  "API_V1_THREAD_PARTIAL_UPDATE_FAILED"
export const API_V1_THREAD_DELETE = "API_V1_THREAD_DELETE"
export const API_V1_THREAD_DELETE_SUCCEEDED = "API_V1_THREAD_DELETE_SUCCEEDED"
export const API_V1_THREAD_DELETE_FAILED = "API_V1_THREAD_DELETE_FAILED"
export const API_V1_THREADACTION_LIST = "API_V1_THREADACTION_LIST"
export const API_V1_THREADACTION_LIST_SUCCEEDED =
  "API_V1_THREADACTION_LIST_SUCCEEDED"
export const API_V1_THREADACTION_LIST_FAILED = "API_V1_THREADACTION_LIST_FAILED"
export const API_V1_THREADACTION_CREATE = "API_V1_THREADACTION_CREATE"
export const API_V1_THREADACTION_CREATE_SUCCEEDED =
  "API_V1_THREADACTION_CREATE_SUCCEEDED"
export const API_V1_THREADACTION_CREATE_FAILED =
  "API_V1_THREADACTION_CREATE_FAILED"
export const API_V1_THREADACTION_READ = "API_V1_THREADACTION_READ"
export const API_V1_THREADACTION_READ_SUCCEEDED =
  "API_V1_THREADACTION_READ_SUCCEEDED"
export const API_V1_THREADACTION_READ_FAILED = "API_V1_THREADACTION_READ_FAILED"
export const API_V1_THREADACTION_UPDATE = "API_V1_THREADACTION_UPDATE"
export const API_V1_THREADACTION_UPDATE_SUCCEEDED =
  "API_V1_THREADACTION_UPDATE_SUCCEEDED"
export const API_V1_THREADACTION_UPDATE_FAILED =
  "API_V1_THREADACTION_UPDATE_FAILED"
export const API_V1_THREADACTION_PARTIAL_UPDATE =
  "API_V1_THREADACTION_PARTIAL_UPDATE"
export const API_V1_THREADACTION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_THREADACTION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_THREADACTION_PARTIAL_UPDATE_FAILED =
  "API_V1_THREADACTION_PARTIAL_UPDATE_FAILED"
export const API_V1_THREADACTION_DELETE = "API_V1_THREADACTION_DELETE"
export const API_V1_THREADACTION_DELETE_SUCCEEDED =
  "API_V1_THREADACTION_DELETE_SUCCEEDED"
export const API_V1_THREADACTION_DELETE_FAILED =
  "API_V1_THREADACTION_DELETE_FAILED"
export const API_V1_THREADMEMBER_LIST = "API_V1_THREADMEMBER_LIST"
export const API_V1_THREADMEMBER_LIST_SUCCEEDED =
  "API_V1_THREADMEMBER_LIST_SUCCEEDED"
export const API_V1_THREADMEMBER_LIST_FAILED = "API_V1_THREADMEMBER_LIST_FAILED"
export const API_V1_THREADMEMBER_CREATE = "API_V1_THREADMEMBER_CREATE"
export const API_V1_THREADMEMBER_CREATE_SUCCEEDED =
  "API_V1_THREADMEMBER_CREATE_SUCCEEDED"
export const API_V1_THREADMEMBER_CREATE_FAILED =
  "API_V1_THREADMEMBER_CREATE_FAILED"
export const API_V1_THREADMEMBER_READ = "API_V1_THREADMEMBER_READ"
export const API_V1_THREADMEMBER_READ_SUCCEEDED =
  "API_V1_THREADMEMBER_READ_SUCCEEDED"
export const API_V1_THREADMEMBER_READ_FAILED = "API_V1_THREADMEMBER_READ_FAILED"
export const API_V1_THREADMEMBER_UPDATE = "API_V1_THREADMEMBER_UPDATE"
export const API_V1_THREADMEMBER_UPDATE_SUCCEEDED =
  "API_V1_THREADMEMBER_UPDATE_SUCCEEDED"
export const API_V1_THREADMEMBER_UPDATE_FAILED =
  "API_V1_THREADMEMBER_UPDATE_FAILED"
export const API_V1_THREADMEMBER_PARTIAL_UPDATE =
  "API_V1_THREADMEMBER_PARTIAL_UPDATE"
export const API_V1_THREADMEMBER_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_THREADMEMBER_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_THREADMEMBER_PARTIAL_UPDATE_FAILED =
  "API_V1_THREADMEMBER_PARTIAL_UPDATE_FAILED"
export const API_V1_THREADMEMBER_DELETE = "API_V1_THREADMEMBER_DELETE"
export const API_V1_THREADMEMBER_DELETE_SUCCEEDED =
  "API_V1_THREADMEMBER_DELETE_SUCCEEDED"
export const API_V1_THREADMEMBER_DELETE_FAILED =
  "API_V1_THREADMEMBER_DELETE_FAILED"
export const API_V1_USER_LIST = "API_V1_USER_LIST"
export const API_V1_USER_LIST_SUCCEEDED = "API_V1_USER_LIST_SUCCEEDED"
export const API_V1_USER_LIST_FAILED = "API_V1_USER_LIST_FAILED"
export const API_V1_USER_CREATE = "API_V1_USER_CREATE"
export const API_V1_USER_CREATE_SUCCEEDED = "API_V1_USER_CREATE_SUCCEEDED"
export const API_V1_USER_CREATE_FAILED = "API_V1_USER_CREATE_FAILED"
export const API_V1_USER_READ = "API_V1_USER_READ"
export const API_V1_USER_READ_SUCCEEDED = "API_V1_USER_READ_SUCCEEDED"
export const API_V1_USER_READ_FAILED = "API_V1_USER_READ_FAILED"
export const API_V1_USER_UPDATE = "API_V1_USER_UPDATE"
export const API_V1_USER_UPDATE_SUCCEEDED = "API_V1_USER_UPDATE_SUCCEEDED"
export const API_V1_USER_UPDATE_FAILED = "API_V1_USER_UPDATE_FAILED"
export const API_V1_USER_PARTIAL_UPDATE = "API_V1_USER_PARTIAL_UPDATE"
export const API_V1_USER_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_USER_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_USER_PARTIAL_UPDATE_FAILED =
  "API_V1_USER_PARTIAL_UPDATE_FAILED"
export const API_V1_USER_DELETE = "API_V1_USER_DELETE"
export const API_V1_USER_DELETE_SUCCEEDED = "API_V1_USER_DELETE_SUCCEEDED"
export const API_V1_USER_DELETE_FAILED = "API_V1_USER_DELETE_FAILED"
export const API_V1_VERIFICATIONCODE_LIST = "API_V1_VERIFICATIONCODE_LIST"
export const API_V1_VERIFICATIONCODE_LIST_SUCCEEDED =
  "API_V1_VERIFICATIONCODE_LIST_SUCCEEDED"
export const API_V1_VERIFICATIONCODE_LIST_FAILED =
  "API_V1_VERIFICATIONCODE_LIST_FAILED"
export const API_V1_VERIFICATIONCODE_CREATE = "API_V1_VERIFICATIONCODE_CREATE"
export const API_V1_VERIFICATIONCODE_CREATE_SUCCEEDED =
  "API_V1_VERIFICATIONCODE_CREATE_SUCCEEDED"
export const API_V1_VERIFICATIONCODE_CREATE_FAILED =
  "API_V1_VERIFICATIONCODE_CREATE_FAILED"
export const API_V1_VERIFICATIONCODE_READ = "API_V1_VERIFICATIONCODE_READ"
export const API_V1_VERIFICATIONCODE_READ_SUCCEEDED =
  "API_V1_VERIFICATIONCODE_READ_SUCCEEDED"
export const API_V1_VERIFICATIONCODE_READ_FAILED =
  "API_V1_VERIFICATIONCODE_READ_FAILED"
export const API_V1_VERIFICATIONCODE_UPDATE = "API_V1_VERIFICATIONCODE_UPDATE"
export const API_V1_VERIFICATIONCODE_UPDATE_SUCCEEDED =
  "API_V1_VERIFICATIONCODE_UPDATE_SUCCEEDED"
export const API_V1_VERIFICATIONCODE_UPDATE_FAILED =
  "API_V1_VERIFICATIONCODE_UPDATE_FAILED"
export const API_V1_VERIFICATIONCODE_PARTIAL_UPDATE =
  "API_V1_VERIFICATIONCODE_PARTIAL_UPDATE"
export const API_V1_VERIFICATIONCODE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_VERIFICATIONCODE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_VERIFICATIONCODE_PARTIAL_UPDATE_FAILED =
  "API_V1_VERIFICATIONCODE_PARTIAL_UPDATE_FAILED"
export const API_V1_VERIFICATIONCODE_DELETE = "API_V1_VERIFICATIONCODE_DELETE"
export const API_V1_VERIFICATIONCODE_DELETE_SUCCEEDED =
  "API_V1_VERIFICATIONCODE_DELETE_SUCCEEDED"
export const API_V1_VERIFICATIONCODE_DELETE_FAILED =
  "API_V1_VERIFICATIONCODE_DELETE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
